### ISSUE TITLE
0.8 release 🔔

### ISSUE THREAD

**Issue by Huluti** [Huluti/ImCompressor#24]
HI! A new release will be out soon to fix #19.

### Added
- Add an option to whether keep or not metadata of images.

### Changed
- Replace mozjpeg lib by jpegoptim.
- Update translations.

In order to have a good release I need some help of the translators to update their translations (very few changes) and ideally, it would be nice if some people test the new version from the source code to detect possible bugs.

**TODO before 0.8 release:**
- [x] update translations
    - [x] de :@Etamuk
    - [x] nl: @Vistaus
    - [x] it: @albanobattistella
- [x] test the soft

Thank's in advance! 🔔

**Comment by Huluti** [comment]
@yochananmarqos there will be some changes to make for 0.8 in AUR (not yet released). mozjpeg has been replaced by jpegoptim.

**Comment by manekenpix** [comment]
Hey @Huluti, are you planning to add more languages? I'm a native Spanish speaker, so I could help with that. Also, I have a year of experience with python working on different projects.

**Comment by Huluti** [comment]
@manekenpix hi! We can add every language you want. Just make a PR after creating a po file based on this pot file: https://github.com/Huluti/ImCompressor/blob/master/po/imcompressor.pot

**Comment by Etamuk** [comment]
> HI! A new release will be out soon to fix #19.
> 
> ### Added
> * Add an option to whether keep or not metadata of images.
> 
> ### Changed
> * Replace mozjpeg lib by jpegoptim.
> * Update translations.
> 
> In order to have a good release I need some help of the translators to update their translations (very few changes) and ideally, it would be nice if some people test the new version from the source code to detect possible bugs.
> 
> **TODO before 0.8 release:**
> 
> * [ ]  update translations
>   
>   * [ ]  de :@Etamuk
>   * [ ]  nl: @Vistaus
>   * [x]  it: @albanobattistella
> * [x]  test the soft
> 
> Thank's in advance!

Translation DE done :-)

**Comment by Vistaus** [comment]
Done! https://github.com/Huluti/ImCompressor/pull/28 :smiley_cat:

**Comment by pauloxnet** [comment]
I read online about this project and I think it's a good work. 👍

I'm using Trimage to compress images to use in web projects and I need to strip every metadata and compress them as much as possible.

The best features of this project for me is mozjpeg support because it has a better compression level than jpegoptim but I read just now that you replaced it in latest commits and it's a pity.

Can you restore mozjpeg in the project and permit users to choose if use jpegoptim (and preserve metadata) or use mozjpeg (a have better compression and no metadata) ?

**Comment by yochananmarqos** [comment]
> The best features of this project for me is mozjpeg support because it has a better compression level than jpegoptim but I read just now that you replaced it in latest commits and it's a pity.

[Are you sure about that? ](https://libjpeg-turbo.org/About/Mozjpeg) It'll never be merged into `libjpeg-turbo` and Mozilla hasn't had a stable release in over a year.

**Comment by pauloxnet** [comment]
As reported in the libjpeg-turbo you linked in your comment and also in the [mozjpeg](https://github.com/mozilla/mozjpeg) README:

> _"MozJPEG makes tradeoffs that are intended to benefit Web use cases and focuses solely on improving encoding, so it's best used as part of a Web encoding workflow."_

As I've wrote in my comment I'm interested in the "web encoding workflow", and in this context the most important thing is compression level at the same quality, compression or decompression performance are secondary because usually you compress one time your image but a lot of people download them from your website, and smaller is the file better is the navigation experience.

**Comment by Huluti** [comment]
@pauloxnet When I used MozJPEG, I used cjpeg and jpgtran. cjpeg has not parameter to control metadata keeping. Moreover, it requires a bit of gymnastic to overwrite the original image. jpegoptim has very good results, don't worry.

**Comment by Huluti** [comment]
0.8 released!

**Comment by pauloxnet** [comment]
I'll try for next versions to open a PR to add again mozjpeg as optional choice.
